### ISSUE TITLE
Impossible to link with GitHub

### ISSUE THREAD

**Issue by DoubleTroublePy** [datreks/codetime-web#135] opened 2021-07-01 06:28 UTC
When I try to connect my GitHub account the site redirects me to this link 
https://codetime-api.datreks.com/auth/github/callback?code=0853049f2813f594af02&state=%2F.
The showed message is the following  ![Cattura](https://user-images.githubusercontent.com/73990389/124075774-a7ef2b80-da45-11eb-8873-504bdc65d0d5.PNG) and for this reason, I can't get the token key.

**Comment by ronilaukkarinen** [comment] 2021-07-04 14:45
Same here.

**Comment by MrMasrozYTLIVE** [comment] 2021-07-05 10:31
Same

**Comment by MrMasrozYTLIVE** [comment] 2021-07-05 10:32
@Jannchie Can you fix it?

**Comment by hokkqi** [comment] 2021-07-07 09:10
Still happening for me as well.

**Comment by MrMasrozYTLIVE** [comment] 2021-07-07 21:17
@hokkqi and will. @Jannchie is lazy

**Comment by hokkqi** [comment] 2021-07-07 21:20
or just busy

**Comment by Jannchie** [comment] 2021-07-08 01:38
I'm sorry I wasn't able to fix it immediately. It was a back-end problem, and I was in charge of the front end. 

The back-end engineers are really busy these days, and I have been urging them. 

Thank you for your patience.

**Comment by si9ma** [comment] 2021-07-08 03:57
@hokkqi @MrMasrozYTLIVE @ronilaukkarinen @DoubleTroublePy fixed! Sorry, I have been too busy recently. The problem is caused by too much data. We will expand the storage space in the future.

**Comment by hokkqi** [comment] 2021-07-14 05:57
request to close this issue?

**Closed** 2021-07-14 06:01 UTC
